apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: repo-lincoln-center
spec:
  serviceName: "service-lincoln-center"
  replicas: 1
  selector:
    matchLabels:
      app: content-repo
      venue_name: lincoln-center
  template:
    metadata:
      labels:
        app: content-repo
        venue_name: lincoln-center
    spec:
      containers:
      - name: content-repo
        image: geo-app/content-repo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /app/storage
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: service-lincoln-center
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    venue_name: lincoln-center