apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: repo-village-vanguard
spec:
  serviceName: "service-village-vanguard"
  replicas: 1
  selector:
    matchLabels:
      app: content-repo
      venue_name: village-vanguard
  template:
    metadata:
      labels:
        app: content-repo
        venue_name: village-vanguard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: area
                operator: In
                values:
                - village-vanguard
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "edge-node"
        effect: "NoSchedule"
      containers:
      - name: content-repo
        image: geo-app/content-repo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: storage
          mountPath: /app/storage
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-village-vanguard
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    venue_name: village-vanguard